#!/bin/bash
#PBS -N build.pbs
#PBS -q paidq
#PBS -P 95b3beda-8f4a-41a6-ac94-0aaad86bfd9d
#PBS -M RSCCoreApp@seattlechildrens.org
#PBS -l select=1:mem=16gb:ncpus=1
#PBS -j oe
#PBS -m a
#PBS -o /active/taylor_s/build/RPDEV/cutandrun_nf/logs/

set -eou pipefail

# Set-up conda 
# source ~/.bashrc #configures your shell to use conda activate
module load apptainer 
apptainer pull --force docker://mambaorg/micromamba:1.5.5

# bamboo automation assumes workingdir is environment variable TEMP_DIR passed in from qsub -v
cd $TEMP_DIR

echo "create artifact dir"
mkdir -p artifacts

# apptainer exec 

# echo "build the conda environment"
# mamba env create -f env/nextflow.yaml --name 'nxf_temp'

# echo "activate conda environment"
# conda activate nxf_temp


# echo "create artifacts"
# # create a copy of run script with the test config 
# sed -E "s/(NFX_CONFIG=).+/\1..\/nextflow_test.config/" main_run.sh > artifacts/bamboo_main_run.sh
# chmod +x artifacts/bamboo_main_run.sh

# run the pipeline using the default parameters
# ./artifacts/bamboo_main_run.sh --outdir './artifacts/results/mouse'

# run the pipeline using the default parameters and building the bowtie indexes
# ./artifacts/bamboo_main_run.sh --outdir './artifacts/results/mouse' --build_index 'true' --build_spike_index 'true'

# run with different executors 

# run different entry points

