#!/bin/bash
#PBS -N build.pbs
#PBS -q paidq
#PBS -P 95b3beda-8f4a-41a6-ac94-0aaad86bfd9d
#PBS -M RSCCoreApp@seattlechildrens.org
#PBS -l select=1:mem=16gb:ncpus=1
#PBS -j oe
#PBS -m a
#PBS -o /active/taylor_s/build/RPDEV/cutandrun_nf/logs/

set -eou pipefail

# Set-up nexflow conda image
module load apptainer 
export APPTAINERENV_APPEND_PATH="/opt/conda/bin"
DATE=$(date +%F)
IMAGE=nxf_${DATE}.sif
# print out the nextflow version information 
apptainer exec $IMAGE /bin/bash -c "nextflow -version"

# bamboo automation assumes workingdir is environment variable TEMP_DIR passed in from qsub -v
cd $TEMP_DIR
echo "create artifact dir"
mkdir -p artifacts

echo "create artifacts"
# run the pipeline using the default parameters
cp bamboo/bamboo_main_run.sh ./artifacts
# apptainer exec $IMAGE /bin/bash -c "./bamboo/bamboo_main_run.sh --outdir './artifacts/results/mouse' "

# run the pipeline using the default parameters and building the bowtie indexes
# ./artifacts/bamboo_main_run.sh --outdir './artifacts/results/mouse' --build_index 'true' --build_spike_index 'true'

# run with different executors 

# run different entry points

