#!/bin/bash
#PBS -N build.pbs
#PBS -q paidq
#PBS -P 95b3beda-8f4a-41a6-ac94-0aaad86bfd9d
#PBS -M RSCCoreApp@seattlechildrens.org
#PBS -l select=1:mem=16gb:ncpus=1
#PBS -l walltime=08:00:00
#PBS -j oe
#PBS -m a
#PBS -o /active/taylor_s/build/RPDEV/cutandrun_nf/logs/

set -eou pipefail

# bamboo automation assumes workingdir is environment variable TEMP_DIR passed in from qsub -v
cd $TEMP_DIR

# Set-up nexflow conda image
module load apptainer 
DATE=$(date +%F)
IMAGE=nxf_${DATE}.sif

# nextflow is installed in a non-standard directory in the container
# see https://apptainer.org/docs/user/main/environment_and_metadata.html#manipulating-path
# export APPTAINERENV_APPEND_PATH="/opt/conda/bin:/depot/apps/apptainer/1.1.9/bin:/opt/pbspro/2020.1/bin"
export APPTAINERENV_APPEND_PATH="/opt/conda/bin"

# print out the software version information 
mamba --version
apptainer --version
# apptainer exec $IMAGE /bin/bash -c "nextflow -version"

# apptainer exec $IMAGE -B /opt/pbspro/2020.1 -B /depot/apps/apptainer/1.1.9/ /bin/bash -c "nextflow -version"
# apptainer shell -B $PWD -B /opt/pbspro/2020.1 -B /depot/apps/apptainer/1.1.9/ $IMAGE

echo "mamba on svc account"
mamba --help
mamba env list

echo "create new mamba environment"
mamba env create --quiet --force -f env/nextflow.yaml --name "nxf_temp"

echo "create artifact dir"
mkdir -p artifacts

echo "create artifacts"
# run the pipeline using the default parameters
cp bamboo/bamboo_main_run.sh ./artifacts
# apptainer exec $IMAGE /bin/bash -c "./bamboo/bamboo_main_run.sh --outdir './artifacts/results/mouse' "

# run the pipeline using the default parameters and building the bowtie indexes
# ./artifacts/bamboo_main_run.sh --outdir './artifacts/results/mouse' --build_index 'true' --build_spike_index 'true'

# run with different executors 

# run different entry points

